---
# tasks file for docker_install

- name: Ensure we have reached the docker_install tasks
  debug:
    msg: "Starting docker_install tasks"

- name: Copy Docker installation script to the target machine
  copy:
    src: ../files/docker_script.sh
    dest: /tmp/docker_script.sh
    mode: '0755'

- name: Run Docker installation script
  command: /tmp/docker_script.sh

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker CE and CLI
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: latest

- name: Install Docker plugins
  apt:
    name:
      - containerd.io
      - docker-buildx-plugin
    state: latest

- name: Install Docker compose
  apt:
    name:
      - docker-compose-plugin
    state: latest

- name: Verify Docker installation
  command: docker --version
