---
# tasks file for inception_setup
- name: Copy inception files into the instance
  copy:
    src: srcs/
    dest: /inception

- name: Create data folder
  file:
    path: /data
    state: directory
    mode: '0755'

- name: Create database folder
  file:
    path: /data/database
    state: directory
    mode: '0755'

- name: Create public folder
  file:
    path: /data/public
    state: directory

- name: Generate .env file for each VM
  template:
    src: env.j2
    dest: "/inception/.env"
    mode: '0644'
  vars:
    vm_ip: "{{ ansible_host }}"
