---
# tasks file for deploy_website
- name: Ensure we have reached the deploy_website tasks
  debug:
    msg: "Starting deploy_website tasks"

- name: Deploy wordpress site
  command: docker compose -p inception -f /inception/docker-compose.yml up --build -d

- name: Confirm deployment
  debug:
    msg: "Done"