- name: Install and configure Docker on GCP instance
  hosts: all
  # hosts: transcendence42.rocks
  become: yes
  roles:
      - test_deployment
    # - packet_upgrade
    # - docker_install
    # - docker_config
    # - inception_setup