- name: Install, Configure Docker on GCP instance and deploy Wordpress Website
  hosts: all
  become: yes
  roles:
    # - test_deployment
    - packet_upgrade
    - docker_install
    - docker_config
    - inception_setup
    - deploy_website